version: '3'
services:
###############################
   cassandra0:
    image: cassandra
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199
    volumes:
      - "cassandra-data:/var/lib/cassandra"
      - "cassandra-data:/home/cassandra/.cassandra"
      - "./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
      - "./init.sh:/init.sh"
    
    entrypoint:
      - /bin/bash
      - /init.sh
###############################
   cassandra1:
    image: cassandra
    container_name: cassandra1
    ports:
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed

###############################
   sparkmaster:
    image: spark
    container_name: spark_master
    ports:
      - 8080:8080
volumes:
  cassandra-data: {}
