version: '2'

services:

# Cassandra Cluster #
   cassandra0:
    image: cassandra
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199
    volumes:
     - cassandra-data:/var/lib/cassandra
     - ./cassandra/init.cql:/init.cql
   
   cassandra1:
    image: cassandra
    container_name: cassandra1
    ports:
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed

################################## 
# Commented out for memory purposes
#   cassandra2:
#    image: cassandra
#    container_name: cassandra2
#    ports:
#     - 9242:9042
#    links:
#     - cassandra0:seed
#    environment:
#     - CASSANDRA_SEEDS=seed
###################################

# Spark Cluster #
   sparkmaster:
    image: spark
    container_name: sparkmaster
    hostname: sparkmaster
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
      - "7077:7077"
    volumes: 
      - ./ml_data/SMSSpamCollection.txt:/SMSSpamCollection.txt
      - ./spark_docker/spark_jars/WordCountTest.jar:/test.jar
      - ./spark_docker/spark_jars/WordCountWorking.jar:/test1.jar


   sparkworker:
    image: sparkworker
    container_name: sparkworker
    tty: true
    stdin_open: true
    ports:
      - "8081:8081"
    depends_on:
      - sparkmaster

   sparkworker2:
    image: sparkworker
    container_name: sparkworker2
    tty: true
    stdin_open: true
    ports:
      - "8082:8081"
    depends_on:
      - sparkmaster

# Spark Jobserver # 
   sparkjobserver:
    image: velvia/spark-jobserver:0.6.2.mesos-0.28.1.spark-1.6.1
    container_name: jobserver
    ports:
      - "8091:8090"
    links:
      - sparkmaster
    depends_on:
      - sparkmaster
    environment:
      SPARK_MASTER: spark://sparkmaster:7077
    volumes: 
      - ./ml_data/SMSSpamCollection.txt:/SMSSpamCollection.txt
      - ./spark_docker/spark_jars/WordCountTest.jar:/test.jar
      - ./spark_docker/spark_jars/WordCountWorking.jar:/test1.jar

# Zeppelin #
   zepplin:
    image: oonlyo/zeppelin:0.8
    container_name: zeppelin
    environment:
      ZEPPELIN_PORT: 8090
      MASTER: spark://sparkmaster:7077
    ports:
      - 8083:8090
    links:
      - sparkmaster
    volumes: 
      - ./ml_data/SMSSpamCollection.txt:/SMSSpamCollection.txt



volumes:
  cassandra-data: {}



