version: '3'

services:

   cassandra0:
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./cassandra/init.cql:/init.cql
    

#    ports:
#      - "9043:9042" 
#    volumes:
#      - cassandra-data:/var/lib/cassandra
#      - cassandra-data:/home/cassandra/.cassandra

######################
   sparkmaster:
    image: spark
    container_name: sparkmaster
    hostname: sparkmaster
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
      - "7077:7077"

      
   sparkworker:
    image: sparkworker
    container_name: sparkworker
    tty: true
    stdin_open: true
    ports:
      - "8081:8081"
    depends_on:
      - sparkmaster

   sparkworker2:
    image: sparkworker
    container_name: sparkworker2
    tty: true
    stdin_open: true
    ports:
      - "8082:8081"
    depends_on:
      - sparkmaster

volumes:
  cassandra-data: {}
