version: '2'

services:

   cassandra0:
    image: cassandra
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199
    volumes:
     - cassandra-data:/var/lib/cassandra
     - ./init.cql:/init.cql
###############################
   cassandra1:
    image: cassandra
    container_name: cassandra1
    ports:
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed

###############################
   cassandra2:
    image: cassandra
    container_name: cassandra2
    ports:
     - 9242:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed

#    ports:
#      - "9043:9042"
#    volumes:
#      - cassandra-data:/var/lib/cassandra
#      - cassandra-data:/home/cassandra/.cassandra

######################
   sparkmaster:
    image: spark
    container_name: sparkmaster
    hostname: sparkmaster
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
      - "7077:7077"


   sparkworker:
    image: sparkworker
    container_name: sparkworker
    tty: true
    stdin_open: true
    ports:
      - "8081:8081"
    depends_on:
      - sparkmaster

   sparkworker2:
    image: sparkworker
    container_name: sparkworker2
    tty: true
    stdin_open: true
    ports:
      - "8082:8081"
    depends_on:
      - sparkmaster

   sparkjobserver:
    image: velvia/spark-jobserver:0.6.2.mesos-0.28.1.spark-1.6.1
    container_name: jobserver
    ports:
      - "8091:8090"
    links:
      - sparkmaster
    environment:
      SPARK_MASTER: sparkmaster

   zeppelin:
    image: oonlyo/zeppelin:0.8
    container_name: zeppelin
    ports:
      - 8090:8090
    links:
      - sparkmaster
    environment:
      ZEPPELIN_PORT: 8090

   webapp:
    image: webapp
    container_name: webapp
    ports:
      - 80:8080
    links:
      - cassandra0:cassandra


volumes:
  cassandra-data: {}
